// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type DailyLog struct {
	ID     int64
	UserID int64
	Date   string
	Count  int64
}

type MonthlyGoal struct {
	ID    int64
	Year  int64
	Month int64
	Goal  int64
}

type User struct {
	ID        int64
	Name      string
	CreatedAt sql.NullTime
}
