// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCombinedMonthlyTotal = `-- name: GetCombinedMonthlyTotal :one
SELECT COALESCE(SUM(count), 0) AS total FROM daily_logs
WHERE date LIKE ?
`

func (q *Queries) GetCombinedMonthlyTotal(ctx context.Context, date string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCombinedMonthlyTotal, date)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getDailyLog = `-- name: GetDailyLog :one
SELECT id, user_id, date, count FROM daily_logs
WHERE user_id = ? AND date = ?
`

type GetDailyLogParams struct {
	UserID int64
	Date   string
}

func (q *Queries) GetDailyLog(ctx context.Context, arg GetDailyLogParams) (DailyLog, error) {
	row := q.db.QueryRowContext(ctx, getDailyLog, arg.UserID, arg.Date)
	var i DailyLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Count,
	)
	return i, err
}

const getMonthlyGoal = `-- name: GetMonthlyGoal :one
SELECT id, year, month, goal FROM monthly_goals
WHERE year = ? AND month = ?
`

type GetMonthlyGoalParams struct {
	Year  int64
	Month int64
}

func (q *Queries) GetMonthlyGoal(ctx context.Context, arg GetMonthlyGoalParams) (MonthlyGoal, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyGoal, arg.Year, arg.Month)
	var i MonthlyGoal
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Goal,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserMonthlyTotal = `-- name: GetUserMonthlyTotal :one
SELECT COALESCE(SUM(count), 0) AS total FROM daily_logs
WHERE user_id = ? AND date LIKE ?
`

type GetUserMonthlyTotalParams struct {
	UserID int64
	Date   string
}

func (q *Queries) GetUserMonthlyTotal(ctx context.Context, arg GetUserMonthlyTotalParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUserMonthlyTotal, arg.UserID, arg.Date)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const listAllDailyLogs = `-- name: ListAllDailyLogs :many
SELECT id, user_id, date, count FROM daily_logs
WHERE date LIKE ?
ORDER BY date ASC
`

func (q *Queries) ListAllDailyLogs(ctx context.Context, date string) ([]DailyLog, error) {
	rows, err := q.db.QueryContext(ctx, listAllDailyLogs, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyLog
	for rows.Next() {
		var i DailyLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyLogs = `-- name: ListDailyLogs :many
SELECT id, user_id, date, count FROM daily_logs
WHERE user_id = ? AND date LIKE ?
ORDER BY date DESC
`

type ListDailyLogsParams struct {
	UserID int64
	Date   string
}

func (q *Queries) ListDailyLogs(ctx context.Context, arg ListDailyLogsParams) ([]DailyLog, error) {
	rows, err := q.db.QueryContext(ctx, listDailyLogs, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyLog
	for rows.Next() {
		var i DailyLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, created_at FROM users ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyLog = `-- name: UpsertDailyLog :exec
INSERT INTO daily_logs (user_id, date, count)
VALUES (?, ?, ?)
ON CONFLICT(user_id, date) DO UPDATE SET count = excluded.count
`

type UpsertDailyLogParams struct {
	UserID int64
	Date   string
	Count  int64
}

func (q *Queries) UpsertDailyLog(ctx context.Context, arg UpsertDailyLogParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyLog, arg.UserID, arg.Date, arg.Count)
	return err
}

const upsertMonthlyGoal = `-- name: UpsertMonthlyGoal :exec
INSERT INTO monthly_goals (year, month, goal)
VALUES (?, ?, ?)
ON CONFLICT(year, month) DO UPDATE SET goal = excluded.goal
`

type UpsertMonthlyGoalParams struct {
	Year  int64
	Month int64
	Goal  int64
}

func (q *Queries) UpsertMonthlyGoal(ctx context.Context, arg UpsertMonthlyGoalParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonthlyGoal, arg.Year, arg.Month, arg.Goal)
	return err
}
