// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, name string) (User, error)
	GetCombinedMonthlyTotal(ctx context.Context, date string) (interface{}, error)
	GetDailyLog(ctx context.Context, arg GetDailyLogParams) (DailyLog, error)
	GetMonthlyGoal(ctx context.Context, arg GetMonthlyGoalParams) (MonthlyGoal, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserMonthlyTotal(ctx context.Context, arg GetUserMonthlyTotalParams) (interface{}, error)
	ListAllDailyLogs(ctx context.Context, date string) ([]DailyLog, error)
	ListDailyLogs(ctx context.Context, arg ListDailyLogsParams) ([]DailyLog, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpsertDailyLog(ctx context.Context, arg UpsertDailyLogParams) error
	UpsertMonthlyGoal(ctx context.Context, arg UpsertMonthlyGoalParams) error
}

var _ Querier = (*Queries)(nil)
